modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Evoslab/Cookielicious"

[[mods]]
modId="cookielicious"
version="1.1.3"
displayName="Cookielicious"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="cookielicious.png"
credits="Thanks to Team Abnormals for making Neapolitan"
authors="Evo, Stardust, AvocadoSpud, Nary, EltrutLikes"
description='''
Cookielicious is an addon for Neapolitan that adds more cookie themed items.
'''

[[dependencies.cookielicious]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="neapolitan" 
    mandatory=true 
    versionRange="[1.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"