modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="http://github.com/Evoslab/Cookielicious"

[[mods]]
modId="cookielicious"
version="1.1.3"
displayName="Cookielicious"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="cookielicious.png"
credits="Evo, Stardust, AvocadoSpud, Nary, EltrutLikes, and thanks to Team Abnormals for making Neapolitan"
authors="Evo's Lab"
description='''
Cookielicious is an addon for Neapolitan that adds more cookie themed items.
'''

[[dependencies.cookielicious]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
    modId="neapolitan" 
    mandatory=true 
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cookielicious]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"